# Generated by Django 6.0.4 on 2026-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='related_entity_id',
        ),
        migrations.AddField(
            model_name='category',
            name='api_catalog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
