# Generated by Django 6.0.4 on 2026-04-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_related_entity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='api_catalog_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='application_id',
        ),
        migrations.AddField(
            model_name='document',
            name='api_catalog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
